name:                bitcoin
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/KovalevDima/bitcoin#readme
license:             MIT
author:              Kovalev Dmitry
maintainer:          onarainydayillwinanyway@gmail.com
copyright:           2021 Kovalev Dmitry
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - lens
  - lens-aeson
  - bytestring
  - text
  - http-conduit

executables:
  bitcoin:
    source-dirs:      src
    main:             Main.hs
